export const services = {
  service: [
    {
      serviceType: ["urn:Belkin:service:WiFiSetup:1"],
      serviceId: ["urn:Belkin:serviceId:WiFiSetup1"],
      controlURL: ["/upnp/control/WiFiSetup1"],
      eventSubURL: ["/upnp/event/WiFiSetup1"],
      SCPDURL: ["/setupservice.xml"],
    },
    {
      serviceType: ["urn:Belkin:service:timesync:1"],
      serviceId: ["urn:Belkin:serviceId:timesync1"],
      controlURL: ["/upnp/control/timesync1"],
      eventSubURL: ["/upnp/event/timesync1"],
      SCPDURL: ["/timesyncservice.xml"],
    },
    {
      serviceType: ["urn:Belkin:service:basicevent:1"],
      serviceId: ["urn:Belkin:serviceId:basicevent1"],
      controlURL: ["/upnp/control/basicevent1"],
      eventSubURL: ["/upnp/event/basicevent1"],
      SCPDURL: ["/eventservice.xml"],
    },
    {
      serviceType: ["urn:Belkin:service:firmwareupdate:1"],
      serviceId: ["urn:Belkin:serviceId:firmwareupdate1"],
      controlURL: ["/upnp/control/firmwareupdate1"],
      eventSubURL: ["/upnp/event/firmwareupdate1"],
      SCPDURL: ["/firmwareupdate.xml"],
    },
    {
      serviceType: ["urn:Belkin:service:rules:1"],
      serviceId: ["urn:Belkin:serviceId:rules1"],
      controlURL: ["/upnp/control/rules1"],
      eventSubURL: ["/upnp/event/rules1"],
      SCPDURL: ["/rulesservice.xml"],
    },
    {
      serviceType: ["urn:Belkin:service:metainfo:1"],
      serviceId: ["urn:Belkin:serviceId:metainfo1"],
      controlURL: ["/upnp/control/metainfo1"],
      eventSubURL: ["/upnp/event/metainfo1"],
      SCPDURL: ["/metainfoservice.xml"],
    },
    {
      serviceType: ["urn:Belkin:service:remoteaccess:1"],
      serviceId: ["urn:Belkin:serviceId:remoteaccess1"],
      controlURL: ["/upnp/control/remoteaccess1"],
      eventSubURL: ["/upnp/event/remoteaccess1"],
      SCPDURL: ["/remoteaccess.xml"],
    },
    {
      serviceType: ["urn:Belkin:service:deviceinfo:1"],
      serviceId: ["urn:Belkin:serviceId:deviceinfo1"],
      controlURL: ["/upnp/control/deviceinfo1"],
      eventSubURL: ["/upnp/event/deviceinfo1"],
      SCPDURL: ["/deviceinfoservice.xml"],
    },
    {
      serviceType: ["urn:Belkin:service:smartsetup:1"],
      serviceId: ["urn:Belkin:serviceId:smartsetup1"],
      controlURL: ["/upnp/control/smartsetup1"],
      eventSubURL: ["/upnp/event/smartsetup1"],
      SCPDURL: ["/smartsetup.xml"],
    },
    {
      serviceType: ["urn:Belkin:service:manufacture:1"],
      serviceId: ["urn:Belkin:serviceId:manufacture1"],
      controlURL: ["/upnp/control/manufacture1"],
      eventSubURL: ["/upnp/event/manufacture1"],
      SCPDURL: ["/manufacture.xml"],
    },
  ],
};
